#!/usr/bin/env python3
"""Create missing section index pages."""
import os

BASE = "src/content/docs"

INDEXES = [
    # tasks subdirs
    ("tasks/installation/index.md",
     "Installation",
     "Install go-zero, goctl, and all required tools.",
     "## Contents\n\n- [Install Go](../../../getting-started/installation/go.md) — Install the Go toolchain\n- [Install go-zero](go-zero.md) — Add go-zero to your module\n- [Install goctl](goctl.md) — Code generation tool\n- [Install protoc](protoc.md) — Protocol Buffers compiler\n- [GoLand Plugin](goctl-intellij.md) — JetBrains IDE plugin\n- [VS Code Extension](goctl-vscode.md) — VS Code extension\n",
     "## 内容\n\n- [安装 Go](../../../getting-started/installation/go.md) — 安装 Go 工具链\n- [安装 go-zero](go-zero.md) — 将 go-zero 添加到模块\n- [安装 goctl](goctl.md) — 代码生成工具\n- [安装 protoc](protoc.md) — Protocol Buffers 编译器\n- [GoLand 插件](goctl-intellij.md) — JetBrains IDE 插件\n- [VS Code 插件](goctl-vscode.md) — VS Code 扩展\n",
    ),
    ("tasks/create/index.md",
     "Create a Project",
     "Scaffold a new go-zero project using the CLI, GoLand, or VS Code.",
     "## Contents\n\n- [CLI](command.md) — Create a project from the command line\n- [GoLand](goland.md) — Create a project from JetBrains GoLand\n- [VS Code](vscode.md) — Create a project from Visual Studio Code\n",
     "## 内容\n\n- [CLI](command.md) — 通过命令行创建项目\n- [GoLand](goland.md) — 通过 JetBrains GoLand 创建项目\n- [VS Code](vscode.md) — 通过 Visual Studio Code 创建项目\n",
    ),
    ("tasks/dsl/index.md",
     "DSL",
     "Write go-zero .api and .proto DSL files.",
     "## Contents\n\n- [API Syntax](api.md) — Write `.api` DSL files\n- [Proto Syntax](proto.md) — Write `.proto` files\n",
     "## 内容\n\n- [API 语法](api.md) — 编写 `.api` DSL 文件\n- [Proto 语法](proto.md) — 编写 `.proto` 文件\n",
    ),
    ("tasks/cli/index.md",
     "Code Generation Tasks",
     "Use goctl to generate code from .api and .proto files.",
     "## Contents\n\n- [API Demo Code Generation](api-demo.md) — Generate an HTTP service\n- [API File Formatting](api-format.md) — Format `.api` files\n- [gRPC Demo Code Generation](grpc-demo.md) — Generate a gRPC service\n- [MySQL Model Generation](mysql.md) — Generate MySQL models\n- [MongoDB Model Generation](mongo.md) — Generate MongoDB models\n",
     "## 内容\n\n- [API Demo 代码生成](api-demo.md) — 生成 HTTP 服务\n- [API 文件格式化](api-format.md) — 格式化 `.api` 文件\n- [gRPC Demo 代码生成](grpc-demo.md) — 生成 gRPC 服务\n- [MySQL Model 生成](mysql.md) — 生成 MySQL Model\n- [MongoDB Model 生成](mongo.md) — 生成 MongoDB Model\n",
    ),
    ("tasks/http/index.md",
     "HTTP Service Tasks",
     "Build and run go-zero HTTP services.",
     "## Contents\n\n- [Hello World HTTP Service](helloworld.md) — Build a minimal HTTP service\n",
     "## 内容\n\n- [Hello World HTTP 服务](helloworld.md) — 构建最小化 HTTP 服务\n",
    ),
    ("tasks/grpc/index.md",
     "gRPC Service Tasks",
     "Build and run go-zero gRPC services.",
     "## Contents\n\n- [gRPC Server Quickstart](server/quickstart.md) — Scaffold a gRPC server\n- [gRPC Client Quickstart](client/quickstart.md) — Generate a gRPC client\n",
     "## 内容\n\n- [gRPC 服务端快速上手](server/quickstart.md) — 脚手架 gRPC 服务端\n- [gRPC 客户端快速上手](client/quickstart.md) — 生成 gRPC 客户端\n",
    ),
    ("tasks/grpc/server/index.md",
     "gRPC Server Tasks",
     "Scaffold and run a go-zero gRPC server.",
     "## Contents\n\n- [gRPC Server Quickstart](quickstart.md)\n",
     "## 内容\n\n- [gRPC 服务端快速上手](quickstart.md)\n",
    ),
    ("tasks/grpc/client/index.md",
     "gRPC Client Tasks",
     "Generate and use a go-zero gRPC client.",
     "## Contents\n\n- [gRPC Client Quickstart](quickstart.md)\n",
     "## 内容\n\n- [gRPC 客户端快速上手](quickstart.md)\n",
    ),
    ("tasks/log/index.md",
     "Logging Tasks",
     "Add structured logging to go-zero services.",
     "## Contents\n\n- [Logging](log.md) — Configure and use logx\n",
     "## 内容\n\n- [日志](log.md) — 配置和使用 logx\n",
    ),
    ("tasks/mongo/index.md",
     "MongoDB Tasks",
     "Connect to and query MongoDB in go-zero.",
     "## Contents\n\n- [MongoDB Connection](conn.md) — Create a connection\n- [MongoDB CRUD](curd.md) — Basic CRUD operations\n",
     "## 内容\n\n- [MongoDB 连接](conn.md) — 创建连接\n- [MongoDB CRUD](curd.md) — 基础增删改查\n",
    ),
    ("tasks/mysql/index.md",
     "MySQL Tasks",
     "Connect to and query MySQL in go-zero.",
     "## Contents\n\n- [MySQL Quickstart](mysql.md) — Connect and query MySQL\n",
     "## 内容\n\n- [MySQL 快速上手](mysql.md) — 连接和查询 MySQL\n",
    ),
    ("tasks/queue/index.md",
     "Queue Tasks",
     "Use message queues and delay queues in go-zero.",
     "## Contents\n\n- [Message Queue (Kafka)](message-queue.md) — Publish/subscribe messaging\n- [Delay Queue (Beanstalkd)](delay-queue.md) — Deferred task execution\n",
     "## 内容\n\n- [消息队列（Kafka）](message-queue.md) — 发布/订阅消息\n- [延迟队列（Beanstalkd）](delay-queue.md) — 延迟任务执行\n",
    ),
    ("tasks/redis/index.md",
     "Redis Tasks",
     "Connect to and use Redis in go-zero.",
     "## Contents\n\n- [Redis Quickstart](redis.md) — Connect and run commands\n",
     "## 内容\n\n- [Redis 快速上手](redis.md) — 连接和运行命令\n",
    ),
    ("tasks/static-configuration/index.md",
     "Static Configuration",
     "Load and manage static YAML/JSON configuration files in go-zero.",
     "## Contents\n\n- [Static Configuration](configuration.md) — Load and validate config files\n",
     "## 内容\n\n- [静态配置](configuration.md) — 加载和验证配置文件\n",
    ),
    # components subdirs
    ("components/cache/index.md",
     "Cache Components",
     "In-process and distributed caching components for go-zero.",
     "## Contents\n\n- [Memory Cache](memory-cache.md) — In-process LRU cache\n- [Redis Cache](redis-cache.md) — Distributed Redis cache\n",
     "## 内容\n\n- [内存缓存](memory-cache.md) — 进程内 LRU 缓存\n- [Redis 缓存](redis-cache.md) — 分布式 Redis 缓存\n",
    ),
    ("components/limiter/index.md",
     "Limiter Components",
     "Rate limiting components for go-zero services.",
     "## Contents\n\n- [Period Limiter](peroid.md) — Limit requests per time period\n- [Token Bucket Limiter](token.md) — Token bucket rate limiting\n",
     "## 内容\n\n- [Period Limiter](peroid.md) — 按时间段限流\n- [Token Bucket Limiter](token.md) — 令牌桶限流\n",
    ),
    ("components/log/index.md",
     "Log Components",
     "Structured logging components for go-zero.",
     "## Contents\n\n- [logx](logx.md) — Core structured logger\n- [logc](logc.md) — Context-aware logging\n",
     "## 内容\n\n- [logx](logx.md) — 核心结构化日志记录器\n- [logc](logc.md) — 上下文感知日志记录\n",
    ),
    ("components/observability/index.md",
     "Observability Components",
     "Logging, metrics, and tracing components for go-zero.",
     "## Contents\n\n- [Logging](logging.md) — Structured logging\n- [Metrics](metrics.md) — Prometheus metrics\n- [Tracing](tracing.md) — Distributed tracing\n",
     "## 内容\n\n- [日志](logging.md) — 结构化日志\n- [指标](metrics.md) — Prometheus 指标\n- [追踪](tracing.md) — 分布式追踪\n",
    ),
    ("components/queue/index.md",
     "Queue Components",
     "Message queue components for go-zero.",
     "## Contents\n\n- [Kafka](kafka.md) — Kafka queue component\n- [RabbitMQ](rabbitmq.md) — RabbitMQ queue component\n",
     "## 内容\n\n- [Kafka](kafka.md) — Kafka 队列组件\n- [RabbitMQ](rabbitmq.md) — RabbitMQ 队列组件\n",
    ),
    ("components/resilience/index.md",
     "Resilience Components",
     "Fault tolerance components for go-zero: circuit breaker, rate limiter, timeout, load shedding.",
     "## Contents\n\n- [Circuit Breaker](circuit-breaker.md) — Stop cascading failures\n- [Rate Limiter](rate-limiter.md) — Limit request rates\n- [Timeout](timeout.md) — Enforce operation timeouts\n- [Load Shedding](load-shedding.md) — Reject excess load\n",
     "## 内容\n\n- [熔断器](circuit-breaker.md) — 阻止级联故障\n- [限流器](rate-limiter.md) — 限制请求速率\n- [超时](timeout.md) — 强制操作超时\n- [负载削减](load-shedding.md) — 拒绝超额负载\n",
    ),
    # faq subdirs
    ("faq/deploy/index.md",
     "Deployment FAQ",
     "Frequently asked questions about deploying go-zero services.",
     "## Contents\n\n- [Reducing Binary Size](binary-size.md) — Shrink production binaries\n",
     "## 内容\n\n- [减小二进制体积](binary-size.md) — 缩小生产二进制文件\n",
    ),
    ("faq/http/index.md",
     "HTTP FAQ",
     "Frequently asked questions about the go-zero HTTP server.",
     "## Contents\n\n- [CORS Configuration](cors.md) — Cross-Origin Resource Sharing\n- [File Server](fileserver.md) — Serve static files\n",
     "## 内容\n\n- [CORS 配置](cors.md) — 跨域资源共享\n- [文件服务器](fileserver.md) — 静态文件服务\n",
    ),
    ("faq/log/index.md",
     "Logging FAQ",
     "Frequently asked questions about logging in go-zero.",
     "## Contents\n\n- [Log to File and Console](fileconsole.md) — Output to both destinations\n",
     "## 内容\n\n- [同时输出到文件和控制台](fileconsole.md) — 输出到两个目标\n",
    ),
    # reference subdirs
    ("reference/configuration/index.md",
     "Configuration Reference",
     "Complete configuration reference for go-zero API and RPC services.",
     "## Contents\n\n- [API Config](api-config.md) — HTTP service configuration\n- [RPC Config](rpc-config.md) — gRPC service configuration\n",
     "## 内容\n\n- [API 配置](api-config.md) — HTTP 服务配置\n- [RPC 配置](rpc-config.md) — gRPC 服务配置\n",
    ),
    ("reference/goctl/index.md",
     "goctl Reference",
     "Complete command reference for the goctl code generation tool.",
     "## Contents\n\n- [Commands](commands.md) — All goctl commands\n- [API](api.md) — `goctl api` reference\n- [RPC](rpc.md) — `goctl rpc` reference\n- [Model](model.md) — `goctl model` reference\n",
     "## 内容\n\n- [命令](commands.md) — 所有 goctl 命令\n- [API](api.md) — `goctl api` 参考\n- [RPC](rpc.md) — `goctl rpc` 参考\n- [Model](model.md) — `goctl model` 参考\n",
    ),
    ("reference/releases/index.md",
     "Release Notes",
     "go-zero release notes and migration guides.",
     "## Releases\n\n- [v1.9.0](v1.9.0.md)\n",
     "## 版本\n\n- [v1.9.0](v1.9.0.md)\n",
    ),
]


def write_index(rel_path, title, desc, body):
    full_path = os.path.join(BASE, rel_path)
    if os.path.exists(full_path):
        return False
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    content = f"---\ntitle: {title}\ndescription: {desc}\n---\n\n{body.strip()}\n"
    with open(full_path, 'w') as f:
        f.write(content)
    return True


created = 0
for entry in INDEXES:
    rel_path, title, desc, en_body, zh_body = entry
    if write_index(rel_path, title, desc, en_body):
        print(f"  EN: {rel_path}")
        created += 1
    zh_rel = "zh-cn/" + rel_path
    if write_index(zh_rel, title, desc, zh_body):
        print(f"  ZH: {zh_rel}")
        created += 1

print(f"\nCreated {created} index pages")
